sudo: required

dist: xenial

env:
  global:
    - CAN_FAIL=false
    - RELEASE_TAG_DOWNSTREAM=0

services:
  - docker

language: go

cache:
  directories:
    - $HOME/.cache/go-build

go:
  - 1.14.7

addons:
  apt:
    update: true

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

before_script:
  - make test
  - make verify-src
  - export RELEASE_TAG="$TRAVIS_TAG"
  - export BRANCH="$TRAVIS_BRANCH"

script:
  - make provisioner-nfs-image PROVISIONER_NFS_IMAGE=provisioner-nfs-amd64

after_success:
  - make push PROVISIONER_NFS_IMAGE=provisioner-nfs-amd64

notifications:
  email:
    recipients:
    - kiran.mova@mayadata.io
