---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-rwx-pvc
  #annotaions:
  #  cas.openebs.io/config: |
  #      FilePermissions can we used to modify the owner, group
  #      and file modes of the shared NFS filesystem.   
  #    - name: FilePermissions
  #      data:
  #        UID: "1000"
  #        GID: "2000"
  #        mode: "0744"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "openebs-rwx"
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  replicas: 3
  template:
    metadata:
      labels:
        app: busybox
    spec:
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: openebs-rwx-pvc
      containers:
        - name: busybox
          image: busybox
          command:
            - sh
            - -c
            - 'while true; do touch /mnt/data/index.html; date >> /mnt/data/index.html; hostname >> /mnt/data/index.html; sleep $(($RANDOM % 5 + 5)); tail -1 /mnt/data/index.html; done'
          volumeMounts:
            - name: nfs-volume
              mountPath: /mnt/data
